### ISSUE TITLE
randomlySampleFastq.pl script is missing

### ISSUE THREAD

**Issue by mr-c** [dpastling/DUF1220_simulation#2]
as referenced from https://github.com/dpastling/DUF1220_simulation/blob/49918f98da0104a72487b2a6bde133e1161eea39/code/simulation_baseline/2_trim_replicates.sh#L18 & https://github.com/dpastling/DUF1220_simulation/blob/49918f98da0104a72487b2a6bde133e1161eea39/code/simulation_spikein/2_trim_spikein.sh#L20

**Comment by dpastling** [comment]
Thanks for bringing this to my attention. It looks like a reference to a file not in the repo. I'll see if I can track that down.

**Comment by dpastling** [comment]
The missing script has been added to the repo and the references have been fixed. Passes tests and should hopefully work for you. Please let me know if you have any further issues.
